blog/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include(('users.urls'), namespace='users')),
    path('', include(('blogs.urls'), namespace='blogs')),
]

blogs/urls.py
from django.urls import path, re_path
from . import views

app_name = 'blogs'
urlpatterns = [
    # 主页
    path('', views.index, name='index'),
    path('topics/', views.topics, name='topics'),
    re_path('topics/(?P<topic_id>\d+)/', views.topic, name = 'topic'),
    path('new_topics/', views.new_topic, name='new_topic'),
    re_path('new_entry/(?P<topic_id>\d+)/', views.new_entry, name = 'new_entry'),
    re_path('edit_entry/(?P<entry_id>\d+)/', views.edit_entry, name = 'edit_entry'),
]

users/urls.py
from django.urls import path,include
from django.contrib.auth.views import LoginView
from django.contrib.auth import logout,login, authenticate
from . import views
app_name = 'users'
LoginView.template_name = 'users/login.html'
urlpatterns = [
    #登录页面
    path('login/',LoginView.as_view(),name='login'),
    #注销
    path('logout/',views.logout_view,name='logout'),
    #注册
    path('register/',views.register,name='register'),
    ]

blogs/models.py
from django.db import models

# Create your models here.

class Topic(models.Model):
    #自我介绍的模块
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    #返回模型的字符串表示
    def __str__(self):
        return self.text

class Entry(models.Model):
    #自我介绍的内容
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'
    
    def __str__(self):
        return self.text[:50] + "..."

class IntroduceTitle(models.Model):
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.text

class Introduce(models.Model):
    IntroduceTitle = models.ForeignKey(IntroduceTitle, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    class Meta:
        verbose_name_plural = 'Introductions'
    def __str__(self):
        return self.text[:50] + "..."

users/models.py
from django.db import models

# Create your models here.

blogs/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text':''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text':''}
        widgets = {'text': forms.Textarea(attrs={'cols':80})}

blogs/views.py
from django.shortcuts import render
from .models import Topic, Entry, Introduce, IntroduceTitle
from .forms import TopicForm, EntryForm

from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
    #主页视图
    return render(request, 'blogs/index.html')

def topics(request):
    #显示所有评论
    topics = Topic.objects.order_by('date_added')
    context = {'topics':topics}
    return render(request, 'blogs/topics.html', context)

def topic(request, topic_id):
    #显示单个评论的内容
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic':topic, 'entries':entries}
    return render(request, 'blogs/topic.html', context)

def new_topic(request):
    #添加新的回复
    if request.method != 'POST':
        #未提交数据，创建一个新的表单
        form = TopicForm()
    else:
        #POST提交的数据，对数据进行处理
        form = TopicForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('blogs:topics'))
    context = {'form':form}
    return render(request, 'blogs/new_topic.html', context)

def new_entry(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('blogs:topic', args=[topic_id]))
    context = {'topic':topic, 'form':form}
    return render(request, 'blogs/new_entry.html', context)

def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('blogs:topic', args=[topic.id]))
    context = {'entry':entry, 'topic':topic, 'form':form}
    return render(request, 'blogs/edit_entry.html', context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('blogs:index'))

def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('blogs:index'))
    context = {'form':form}
    return render(request, 'users/register.html', context)

blogs/templates/blogs/base.html
<!doctype html>

{% load static %}

<html lang="en">

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="KBHIT">
    <meta name="generator" content="Jekyll v4.1.1">
    <title>Kyle's Blog</title>

    <link rel="stylesheet" type="text/css" href="/static/css/index.css">
    <script src="/static/js/index.js"></script>

</head>

<body>
    <canvas id="canvas"></canvas>
	<script type="text/javascript">
		var width=window.innerWidth;
		var height=window.innerHeight * 1.5;
		var canvas=document.querySelector("#canvas");
		var context=canvas.getContext("2d");
		var snowArray=[];
 
		canvas.width=width;
		canvas.height=height;
 
		cartoon();
        for(var i=0;i<1000;i++)
        {
			var snow=new Snowflake();
			snowArray.push(snow);
        }
	</script>
    <div class="header">
        <h1>Kyle's Blog</h1>
    </div>

    <div class="topnav">
        <a href="{% url 'blogs:index' %}">主页</a>
        <a href="{% url 'blogs:topics' %}">留言板</a>
        {% if user.is_authenticated %}
        <a href="#">你好, {{ user.username }}.</a>
        <a href="{% url 'users:logout' %}">登出</a>
        {% else %}
        <a href="{% url 'users:login' %}">登录</a>
        <a href="{% url 'users:register' %}">注册</a>
        {% endif %}
    </div>

    <div class="content">
        <div class="center">
            {% block content %}{% endblock content %}
        </div>
    </div>

</body>
</html>

blogs/templates/blogs/edit_entry.html
{% extends "blogs/base.html" %}

{% block content %}
  <p><a href="{% url 'blogs:topic' topic.id %">{{ topic }}</a></p>

  <p>Edit entry:</p>

  <form action="{% url 'blogs:edit_entry' entry.id %}" method='post'>
      {% csrf_token %}
      {{ form.as_p }}
      <button name="submit">保存</button>
  </form>
{% endblock content %}

blogs/templates/blogs/index.html
{% extends "blogs/base.html " %}

{% block content %}
<div class="pic">
    <h1>欢迎来到Kyle's 个人网站~</h1>
    <h2>你可以在这里了解到我的一些个人信息！</h2>
    <h2>也欢迎留言给我提出一些建议！</h2>
    <h2 id = "demo"></h2>
</div>

<div class="row">
    <div class="column side">
      <h2>个人基本信息</h2>
      <p>姓名：杨思恒</p>
      <p>专业：计算机科学与技术</p>
      <p>出生日期：1999-09-12</p>
      <p>学号：18090033026</p>
      <p>QQ：1063062149</p>
      <p>邮箱：1063062149@qq.com</p>
    </div>
    
    <div class="column middle">
      <h2>自我介绍</h2>
      <p>欢迎来到Kyle的个人网站！！！</p>
      <p>大家好！我的名字是杨思恒，现就读于山东省青岛市崂山区沙河子街道的中国海洋大学信息科学与工程学院的计算机科学与技术专业的大三学生！</p>
      <p>处女座20岁，家乡是福建省泉州市鲤城区。</p>
      <p>最爱摸鱼！</p>
      <h2>兴趣爱好</h2>
      <p>动画、游戏、睡觉</p>
      <p>最喜欢的游戏是弹丸论破系列</p>
      <p>最喜欢的动画作品是银之匙、钢之炼金术师</p>
      <h2>教育经历</h2>
      <p>2006年 至 2012年 福建省泉州市通政中心小学毕业</p>
      <p>2012年 至 2015年 福建省泉州第六中学初中部毕业</p>
      <p>2015年 至 2018年 福建省泉州第一中学高中部毕业</p>
      <p>2018年 至 今 中国海洋大学信息科学与工程学院计算机科学与技术专业在读</p>
    </div>
    
</div>
{% endblock content %}

blogs/templates/blogs/new_entry.html
{% extends "blogs/base.html" %}

{% block content %}
  <p><a href="{% url 'blogs:topic' topic.id %">{{ topic }}</a></p>

  <p>Add a new entry:</p>

  <form action="{% url 'blogs:new_entry' topic.id %}" method='post'>
      {% csrf_token %}
      {{ form.as_p }}
      <button name="submit">提交！</button>
  </form>
{% endblock content %}

blogs/templates/blogs/new_topic.html
{% extends "blogs/base.html" %}

{% block content %}
  <p>你想说些什么:</p>

  <form action="{% url 'blogs:new_topic' %}" method='post'>
      {% csrf_token %}
      {{ form.as_p}}
      <button name="submit">留言！</button>
  </form>
{% endblock content %}

blogs/templates/blogs/topic.html
{% extends "blogs/base.html" %}

{% block content %}
<div class="topichead">
  <p>留言: {{ topic }}</p>
  <p>回复:</p>
  <p>
    <a href="{% url 'blogs:new_entry' topic.id %}">我也要回复！</a>
  </p>
</div>
  <div class="topic">
    {% for entry in entries %}
      <h1>{{ entry.date_added|date:'M d, Y H:i' }}</h1>
      <p>{{ entry.text|linebreaks }}</p>
      <p>
          <a href="{% url 'blogs:edit_entry' entry.id %}">编辑</a>
      </p>
      {% empty %}
      There are no entries for this topic yet
      {% endfor %}
  </div>
{% endblock content %}

blogs/templates/blogs/topics.html
{% extends "blogs/base.html" %}

{% block content %}

  <div class="conter"><h1>欢迎留言！</h1>
    <ul>
      {% for topic in topics %}
        <li>
            <a href = "{% url 'blogs:topic' topic.id %}">{{ topic }}</a>
        </li>
      {% empty %}
      <li>No topics have been add yet.</li>
      {% endfor %}
    </ul>
    <a href="{% url 'blogs:new_topic' %}">我也要留言！</a>
  </div>
    

{% endblock content %}

users/templates/users/login.html
{% extends "blogs/base.html" %}\


{% block content %}

<div class="login">
    <h1>欢迎登录</h1>
    {% if form.errors %}
    <p>Your username and password didn't match.Please try again.</p>
    {% endif %}

    <form method='post' action="{% url 'users:login' %}">
    {% csrf_token %}
    {{ form.as_p}}
    <button name="sumbit" class="button" style="vertical-align:middle"><span>登录</span></button>
    <input type="hidden" name="next" value="{% url 'blogs:index' %}" />
    <button type="button" class="button" style="vertical-align:middle" onclick="goBack()"><span>返回</span></button>
    </form>
</div>


{% endblock content %}

users/templates/users/register.html
{% extends "blogs/base.html" %}

{% block content %}
<div class="login">
    <h1>欢迎注册使用！</h1>
</div>
<div class="register">
    <form method='post' action="{% url 'users:register' %}">
        {% csrf_token %}
        {{ form.as_p}}
        <button name="sumbit" class="button" style="vertical-align:middle"><span>注册</span></button>
        <input type="hidden" name="next" value="{% url 'blogs:index' %}" />
        <button type="button" class="button" style="vertical-align:middle" onclick="goBack()"><span>返回</span></button>

    </form>
</div>

{% endblock content %}